version: '3'
 
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD 
      - POSTGRES_DB
    ports:
      - 15432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
 
volumes:
  postgres: